apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcher-service
spec:
  template:
    spec:
      containers:
        - name: dispatcher-service
          volumeMounts:
            - mountPath: /workspace/secrets/rabbitmq
              name: rabbitmq-credentials-volume
      volumes:
        - name: rabbitmq-credentials-volume
          secret:
            secretName: polar-rabbitmq-credentials