apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/jempitman/dispatcher-service/k8s?ref=main

configMapGenerator:
  - behavior: merge
    files:
      - application-staging.yml
    name: dispatcher-service

images:
  - name: dispatcher-service
    newName: ghcr.io/jempitmqn/dispatcher-service
    newTag: latest

replicas:
  - name: dispatcher-service
    count: 1