apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/jempitman/catalog-service/k8s?ref=caaf28c4beb52d95ee41a792983c14ae45b19d0a

patchesStrategicMerge:
- patch-env.yml
- patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: catalog-config

images:
- name: catalog-service
  newName: ghcr.io/jempitman/catalog-service
  newTag: caaf28c4beb52d95ee41a792983c14ae45b19d0a

replicas:
  - name: catalog-service
    count: 2
